---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system 
summary: Para comenzar, revise los front-ends, los back-ends y la configuración de host compatibles. 
---
= Requisitos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Para comenzar, revise los front-ends, los back-ends y la configuración de host compatibles.


NOTE: Para obtener más información sobre los puertos que utiliza Astra Trident, consulte link:../trident-reference/trident-ports.html["aquí"^].



== Front-ends compatibles (orquestadores)

Astra Trident admite varios orquestadores y motores de contenedor, incluidos los siguientes:

* Kubernetes 1.17 o posterior (último: 1.22)
* Mirantis Kubernetes Engine 3.4
* OpenShift 4.7, 4.8, 4.9 (último 4.9)


El operador Trident es compatible con las siguientes versiones:

* Kubernetes 1.17 o posterior (último: 1.22)
* OpenShift 4.7, 4.8, 4.9 (último 4.9)



NOTE: Los usuarios de Red Hat OpenShift Container Platform pueden observar que el archivo initiatorname.iscsi está en blanco si se utiliza una versión inferior a 4.6.8. Este es un error que ha sido identificado por RedHat para ser corregido con OpenShift 4.6.8. Vea esto https://access.redhat.com/errata/RHSA-2020:5259/["aviso de corrección de errores"^]. NetApp le recomienda que utilice Astra Trident en OpenShift 4.7 y posteriores.

Astra Trident también funciona con una gran variedad de ofertas de Kubernetes totalmente gestionadas y gestionadas, como Google Kubernetes Engine (GKE) de Google Cloud, Elastic Kubernetes Services (EKS) de AWS, Azure Kubernetes Service (AKS) y Rancher.



== Back-ends compatibles (almacenamiento)

Para utilizar Astra Trident, se necesitan uno o varios de los siguientes back-ends compatibles:

* Amazon FSX para ONTAP de NetApp
* Azure NetApp Files
* Almacén de datos Astra
* Cloud Volumes ONTAP
* Cloud Volumes Service para AWS
* Cloud Volumes Service para GCP
* FAS/AFF/Seleccione 9.3 o posterior
* Cabina All SAN de NetApp (ASA)
* Software HCI/Element de NetApp 8 o posterior




== Requisitos de funciones

La siguiente tabla resume las funciones disponibles con esta versión de Astra Trident y las versiones de Kubernetes compatible.

[cols="3"]
|===
| Función | La versión de Kubernetes | ¿Se requieren puertas de funciones? 


| CSI Trident  a| 
1.17 y posterior
 a| 
No



| Snapshots de volumen  a| 
1.17 y posterior
 a| 
No



| RVP desde snapshots de volumen  a| 
1.17 y posterior
 a| 
No



| Cambio de tamaño del VP de iSCSI  a| 
1.17 y posterior
 a| 
No



| CHAP bidireccional de ONTAP  a| 
1.17 y posterior
 a| 
No



| Políticas de exportación dinámicas  a| 
1.17 y posterior
 a| 
No



| Operador de Trident  a| 
1.17 y posterior
 a| 
No



| Preparación automática de nodos de trabajo (beta)  a| 
1.17 y posterior
 a| 
No



| Topología CSI  a| 
1.17 y posterior
 a| 
No

|===


== Se probaron sistemas operativos host

De forma predeterminada, Astra Trident se ejecuta en un contenedor y, por lo tanto, se ejecutará en cualquier trabajador de Linux. Sin embargo, estos trabajadores deben poder montar los volúmenes que ofrece Astra Trident con el cliente NFS o iniciador iSCSI estándar, en función de los back-ends que utilice.

Aunque Astra Trident no «admite» oficialmente sistemas operativos específicos, se sabe que las siguientes distribuciones de Linux funcionan:

* Redhat CoreOS 4.2 y 4.3
* RHEL o CentOS 7.4 o posterior
* Ubuntu 18.04 o posterior


La `tridentctl` Utility también se ejecuta en cualquiera de estas distribuciones de Linux.



== Configuración de hosts

En función de los back-end que se estén utilizando, deben instalarse utilidades NFS y/o iSCSI en todos los trabajadores del clúster. Consulte link:../trident-use/worker-node-prep.html["aquí"^] si quiere más información.



== Configuración del sistema de almacenamiento

Es posible que Astra Trident requiera algunos cambios en un sistema de almacenamiento antes de que una configuración de back-end pueda usarlos. Consulte link:../trident-use/backends.html["aquí"^] para obtener más detalles.



== Imágenes de contenedor y las versiones de Kubernetes correspondientes

Para instalaciones con problemas de conexión aérea, la siguiente lista es una referencia de las imágenes de contenedor necesarias para instalar Astra Trident. Utilice la `tridentctl images` comando para verificar la lista de imágenes de contenedor necesarias.

[cols="2"]
|===
| La versión de Kubernetes | Imagen de contenedor 


| v1.17.0  a| 
* netapp/trident:21.10.0
* netapp/trident-autosupport:21.10
* k8s.gcr.io/sig-storage/csi-aprovisionador:v2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
* k8s.gcr.io/sig-storage/csi-reszer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.3.0
* netapp/operador especializado: 21.10.0 (opcional)




| v1.18.0  a| 
* netapp/trident:21.10.0
* netapp/trident-autosupport:21.10
* k8s.gcr.io/sig-storage/csi-aprovisionador:v2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
* k8s.gcr.io/sig-storage/csi-reszer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.3.0
* netapp/operador especializado: 21.10.0 (opcional)




| v1.19.0  a| 
* netapp/trident:21.10.0
* netapp/trident-autosupport:21.10
* k8s.gcr.io/sig-storage/csi-aprovisionador:v2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
* k8s.gcr.io/sig-storage/csi-reszer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.3.0
* netapp/operador especializado: 21.10.0 (opcional)




| v1.20.0  a| 
* netapp/trident:21.10.0
* netapp/trident-autosupport:21.10
* k8s.gcr.io/sig-storage/csi-aprovisionador:v3.0.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
* k8s.gcr.io/sig-storage/csi-reszer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.3.0
* netapp/operador especializado: 21.10.0 (opcional)




| 1.21.0  a| 
* netapp/trident:21.10.0
* netapp/trident-autosupport:21.10
* k8s.gcr.io/sig-storage/csi-aprovisionador:v3.0.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
* k8s.gcr.io/sig-storage/csi-reszer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.3.0
* netapp/operador especializado: 21.10.0 (opcional)




| v1.22.0  a| 
* netapp/trident:21.10.0
* netapp/trident-autosupport:21.10
* k8s.gcr.io/sig-storage/csi-aprovisionador:v3.0.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
* k8s.gcr.io/sig-storage/csi-reszer:v1.3.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrador:v2.3.0
* netapp/operador especializado: 21.10.0 (opcional)


|===

NOTE: En la versión 1.20 de Kubernetes y versiones posteriores, utilice las validadas `k8s.gcr.io/sig-storage/csi-snapshotter:v4.x` la imagen sólo si la `v1` la versión sirve `volumesnapshots.snapshot.storage.k8s.io` CRD. Si la `v1beta1` La versión sirve al CRD con/sin el `v1` versión, utilice la validada `k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` imagen.
